# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AH-8ximU3aPaSIFKnqpMJeplIzRFyCqb
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# =========================
# 1. Physical setup
# =========================
L = 1.0
h0 = 0.0

theta = np.deg2rad(22.0)
theta_dot = 0.0

dt = 0.04
steps = 360

theta_min = np.deg2rad(8.0)
theta_max = np.deg2rad(75.0)

# =========================
# 2. Inextensible line model
# =========================
# Fixed line length. The line does not stretch.
line_length_fixed = 1.58

# Tension is a proxy generated when the fish tries to exceed the fixed line length.
constraint_k = 8.0
constraint_c = 0.35
prev_distance = None

T_desired = 1.0
T_low = 0.82
T_high = 1.18

# =========================
# 3. Fish target model
# =========================
# Fish is modeled as an active disturbance source.
fish_base = np.array([2.0, 0.45, -0.35], dtype=float)
fish_pos = fish_base.copy()

bite_step = 55
regulate_start_step = None

# =========================
# 4. State machine
# =========================
STATE_MONITOR = 0
STATE_HOOK_SET = 1
STATE_REGULATE = 2

state = STATE_MONITOR
hook_set_counter = 0
hook_set_duration = 22

warmup_steps = 20

tension_threshold = 0.25
delta_tension_threshold = 0.06
prev_tension = 0.0

# =========================
# 5. Rod control parameters
# =========================
hook_set_speed = np.deg2rad(2.4)

# Placeholder baseline tension controller
Kp_reg = 0.055
Kd_reg = 0.12
max_theta_rate = np.deg2rad(1.0)

bang_bang_adjust = np.deg2rad(0.25)

control_action = "Hold"

# =========================
# 6. Data storage
# =========================
theta_hist = []
tension_hist = []
state_hist = []
distance_hist = []
delta_tension_hist = []
fish_hist = []
tip_hist = []
action_hist = []
line_mode_hist = []

# =========================
# 7. Simulation loop
# =========================
for t in range(steps):

    # -------------------------
    # Fish intended motion
    # -------------------------
    if state == STATE_MONITOR:
        fish_desired = fish_base.copy()

    elif state == STATE_HOOK_SET:
        # Smooth bite / initial pull motion.
        progress = min(hook_set_counter / hook_set_duration, 1.0)

        pull_offset = np.array([
            0.10 * progress,
            0.00,
            -0.10 * progress
        ])

        fish_desired = fish_base + pull_offset

    elif state == STATE_REGULATE:
        # Slow fish-like disturbance.
        # Fish moves closer/farther to create tension variation.
        tau = t - regulate_start_step

        fish_x = 2.05 + 0.14 * np.sin(0.055 * tau)
        fish_y = 0.45 + 0.05 * np.sin(0.040 * tau)
        fish_z = -0.42 - 0.05 * np.sin(0.050 * tau + 0.8)

        fish_desired = np.array([fish_x, fish_y, fish_z], dtype=float)

    else:
        fish_desired = fish_pos.copy()

    # -------------------------
    # Rod tip from current theta
    # -------------------------
    x_tip = L * np.cos(theta)
    y_tip = 0.0
    z_tip = h0 + L * np.sin(theta)
    tip_pos = np.array([x_tip, y_tip, z_tip])

    # -------------------------
    # Inextensible line constraint
    # -------------------------
    raw_vec = fish_desired - tip_pos
    raw_distance = np.linalg.norm(raw_vec)

    if raw_distance > 1e-8:
        line_dir = raw_vec / raw_distance
    else:
        line_dir = np.zeros(3)

    if prev_distance is None:
        distance_rate = 0.0
    else:
        distance_rate = (raw_distance - prev_distance) / dt

    # Slack mode:
    # fish is inside the fixed line radius, no tension.
    if raw_distance < line_length_fixed:
        fish_pos = fish_desired.copy()
        actual_distance = raw_distance
        tension = 0.0
        line_mode = "Slack"

    # Taut mode:
    # fish tries to move beyond fixed line length.
    # Project fish back onto the fixed-length boundary.
    else:
        fish_pos = tip_pos + line_length_fixed * line_dir
        actual_distance = line_length_fixed

        # Tension proxy from constraint violation and outward rate.
        violation = raw_distance - line_length_fixed
        outward_rate = max(distance_rate, 0.0)

        tension = constraint_k * violation + constraint_c * outward_rate
        tension = max(tension, 0.0)

        line_mode = "Taut"

    delta_tension = tension - prev_tension

    # -------------------------
    # Hook event detection
    # -------------------------
    if state == STATE_MONITOR and t > warmup_steps:
        if t >= bite_step and (tension > tension_threshold or delta_tension > delta_tension_threshold):
            state = STATE_HOOK_SET
            hook_set_counter = 0

    # Reliable demo trigger if tension proxy is too weak at bite time
    if state == STATE_MONITOR and t == bite_step + 2:
        state = STATE_HOOK_SET
        hook_set_counter = 0

    # -------------------------
    # Save current snapshot
    # -------------------------
    theta_hist.append(np.rad2deg(theta))
    tension_hist.append(tension)
    state_hist.append(state)
    distance_hist.append(actual_distance)
    delta_tension_hist.append(delta_tension)
    fish_hist.append(fish_pos.copy())
    tip_hist.append(tip_pos.copy())
    action_hist.append(control_action)
    line_mode_hist.append(line_mode)

    # -------------------------
    # Rod controller
    # -------------------------
    if state == STATE_MONITOR:
        theta_cmd_dot = 0.0
        control_action = "Hold"

    elif state == STATE_HOOK_SET:
        theta_cmd_dot = hook_set_speed
        control_action = "Hook set: raise rod"

        hook_set_counter += 1

        if hook_set_counter >= hook_set_duration:
            state = STATE_REGULATE
            regulate_start_step = t

    elif state == STATE_REGULATE:
        # Baseline tension regulation logic:
        # tension low  -> raise rod slightly
        # tension high -> lower rod slightly
        tension_error = T_desired - tension
        theta_cmd_dot = Kp_reg * tension_error - Kd_reg * theta_dot

        if tension < T_low:
            theta_cmd_dot += bang_bang_adjust
            control_action = "Raise rod: tension low"
        elif tension > T_high:
            theta_cmd_dot -= bang_bang_adjust
            control_action = "Lower rod: tension high"
        else:
            control_action = "Balance near desired tension"

    theta_cmd_dot = np.clip(theta_cmd_dot, -max_theta_rate, max_theta_rate)

    theta_dot = theta_cmd_dot
    theta += theta_dot
    theta = np.clip(theta, theta_min, theta_max)

    prev_distance = raw_distance
    prev_tension = tension

# Convert to arrays
theta_hist = np.array(theta_hist)
tension_hist = np.array(tension_hist)
state_hist = np.array(state_hist)
distance_hist = np.array(distance_hist)
delta_tension_hist = np.array(delta_tension_hist)
fish_hist = np.array(fish_hist)
tip_hist = np.array(tip_hist)
time = np.arange(steps) * dt

# =========================
# 8. Animation
# =========================
def get_state_name(s):
    if s == STATE_MONITOR:
        return "MONITOR"
    elif s == STATE_HOOK_SET:
        return "HOOK_SET"
    return "REGULATE"

fig = plt.figure(figsize=(10, 7))
gs = fig.add_gridspec(2, 2, height_ratios=[2.0, 1.2])

ax_side = fig.add_subplot(gs[0, 0])
ax_top = fig.add_subplot(gs[0, 1])
ax_tension = fig.add_subplot(gs[1, :])

fig.suptitle("1-DOF Fishing Arm: Inextensible Line + Tension Regulation", fontsize=14)

def update(i):
    ax_side.clear()
    ax_top.clear()
    ax_tension.clear()

    tip = tip_hist[i]
    fish = fish_hist[i]
    tension = tension_hist[i]
    theta_deg = theta_hist[i]
    distance = distance_hist[i]
    state_name = get_state_name(state_hist[i])
    action = action_hist[i]
    line_mode = line_mode_hist[i]

    line_style = 'c-' if line_mode == "Taut" else 'c--'

    # -------------------------
    # Side View
    # -------------------------
    ax_side.plot(0, h0, 'ks', markersize=6, label="Base")
    ax_side.plot([0, tip[0]], [h0, tip[2]], 'bo-', linewidth=3.5, markersize=6, label="Rod")
    ax_side.plot(fish[0], fish[2], 'co', markersize=8, label="Fish")
    ax_side.plot([tip[0], fish[0]], [tip[2], fish[2]], line_style, linewidth=2.2, label="Line")

    ax_side.axhline(0, color='gray', linestyle='--', linewidth=1)
    ax_side.text(0.05, 0.03, "Water surface", fontsize=8, color='gray')

    ax_side.set_title("Side View: Pitch Motion")
    ax_side.set_xlim(-0.1, 3.1)
    ax_side.set_ylim(-0.95, 1.15)
    ax_side.set_aspect("equal")
    ax_side.grid(True)
    ax_side.legend(loc="upper right", fontsize=7)

    ax_side.text(0.05, 1.00, f"State: {state_name}", fontsize=9)
    ax_side.text(0.05, 0.86, f"Action: {action}", fontsize=9)
    ax_side.text(0.05, 0.72, f"Mode: {line_mode}", fontsize=9)
    ax_side.text(0.05, 0.58, f"Theta: {theta_deg:.1f} deg", fontsize=9)
    ax_side.text(0.05, 0.44, f"Tension: {tension:.2f}", fontsize=9)
    ax_side.text(0.05, 0.30, f"Distance: {distance:.2f}", fontsize=9)

    # -------------------------
    # Top View
    # -------------------------
    ax_top.plot(0, 0, 'ks', markersize=6, label="Base")
    ax_top.plot([0, tip[0]], [0, tip[1]], 'bo-', linewidth=3.5, markersize=6, label="Rod projection")
    ax_top.plot(fish[0], fish[1], 'co', markersize=8, label="Fish projection")
    ax_top.plot([tip[0], fish[0]], [tip[1], fish[1]], line_style, linewidth=2.2, label="Line projection")

    ax_top.set_title("Top View: Horizontal Projection")
    ax_top.set_xlim(-0.1, 3.1)
    ax_top.set_ylim(-1.1, 1.1)
    ax_top.set_aspect("equal")
    ax_top.grid(True)
    ax_top.legend(loc="upper right", fontsize=7)

    # -------------------------
    # Tension plot
    # -------------------------
    ax_tension.plot(time[:i+1], tension_hist[:i+1], linewidth=2, label="Tension proxy")
    ax_tension.axhline(T_desired, linestyle='--', linewidth=1.2, label="Desired")
    ax_tension.axhline(T_low, linestyle=':', linewidth=1.0, label="Low bound")
    ax_tension.axhline(T_high, linestyle=':', linewidth=1.0, label="High bound")
    ax_tension.axvline(time[i], color='gray', linestyle=':', linewidth=1)

    ax_tension.set_title("Line Tension Regulation")
    ax_tension.set_xlim(time[0], time[-1])
    ax_tension.set_ylim(0, max(1.7, tension_hist.max() * 1.1))
    ax_tension.set_xlabel("Time (s)")
    ax_tension.set_ylabel("Tension proxy")
    ax_tension.grid(True)
    ax_tension.legend(loc="upper right", fontsize=8)

    return []

# Fewer frames to avoid Colab animation-size warning
anim = FuncAnimation(
    fig,
    update,
    frames=range(0, steps, 3),
    interval=70,
    blit=False
)

plt.close(fig)

HTML(anim.to_jshtml())