# -*- coding: utf-8 -*-
"""1DOF-FK&IK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mnlKUgn-dta6Zbn3yhciQf_AI59JnrKn
"""

import numpy as np

# Coordinate frame definition:
#   +x axis: forward direction, pointing from the base toward the rod/fish
#   +y axis: sideways direction, perpendicular to the side-view plane
#   +z axis: vertical upward direction
#
# Rod pitch angle q:
#   q = 0 deg: rod points horizontally along the +x direction
#   q > 0 deg: rod pitches upward toward +z
#   q < 0 deg: rod pitches downward toward -z
#
# Since the current mechanism only has rod pitch and no base yaw,
# the rod tip motion is constrained to the x-z plane, so y remains 0.
#
# Current placeholder parameters:
#   rod_length = 0.3 m
#   q_min = -20 deg
#   q_max = 80 deg
class FishingRodKinematics:
    def __init__(self, rod_length=0.3, q_min=np.deg2rad(-20), q_max=np.deg2rad(80)):
        self.L = rod_length
        self.q_min = q_min
        self.q_max = q_max

    def rot_y(self, q):
        c = np.cos(q)
        s = np.sin(q)

        return np.array([
            [ c, 0, -s, 0],
            [ 0, 1,  0, 0],
            [ s, 0,  c, 0],
            [ 0, 0,  0, 1]
        ])

    def trans_x(self, L):
        return np.array([
            [1, 0, 0, L],
            [0, 1, 0, 0],
            [0, 0, 1, 0],
            [0, 0, 0, 1]
        ])

    def forward_kinematics(self, q):
        q = np.clip(q, self.q_min, self.q_max)

        T = self.rot_y(q) @ self.trans_x(self.L)
        tip_position = T[:3, 3]

        return T, tip_position

    def inverse_kinematics(self, target):
        x, y, z = target

        q = np.arctan2(z, x)
        q = np.clip(q, self.q_min, self.q_max)

        T, tip_position = self.forward_kinematics(q)

        return q, T, tip_position


if __name__ == "__main__":
    rod = FishingRodKinematics(
        rod_length=0.3,
        q_min=np.deg2rad(-20),
        q_max=np.deg2rad(80)
    )

    q = np.deg2rad(25)
    T, tip = rod.forward_kinematics(q)

    print("Transformation matrix:")
    print(T)

    print("Rod tip position:")
    print(tip)

    target = np.array([0.24, 0.0, 0.12])
    q_sol, T_sol, tip_sol = rod.inverse_kinematics(target)

    print("IK angle in degrees:")
    print(np.rad2deg(q_sol))

    print("Reachable tip position:")
    print(tip_sol)